export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_ID = 'GET_ID';
export const GET_NAME = 'GET_NAME';
export const POST_ACTIVITIES = 'POST_ACTIVITIES'
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const FILTER_BY_ACTIVITY = 'FILTER_BY_ACTIVITY'
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT'
export const GET_COUNTRIES_BY_ALPHABET = 'GET_COUNTRIES_BY_ALPHABET'
export const GET_BY_POPULATION = 'GET_BY_POPULATION'
export const GET_RESET = 'GET_RESET'

